document.addEventListener('DOMContentLoaded', () => {
    const inputSection = document.getElementById('input-section');
    const intentInput = document.getElementById('intent-input');
    const generateBtn = document.getElementById('generate-btn');
    const presetBtns = document.querySelectorAll('.preset-btn');
    const pipelineSection = document.getElementById('pipeline-section');
    const outputSection = document.getElementById('output-section');
    const steps = document.querySelectorAll('.step');
    const progressFills = document.querySelectorAll('.progress-fill');

    // DOM elements to update
    const schemaOutput = document.getElementById('schema-output');
    const tableBody = document.getElementById('table-body');
    const metricDepthVal = document.getElementById('metric-depth-val');
    const metricDepthFill = document.getElementById('metric-depth-fill');
    const metricAdvVal = document.getElementById('metric-adv-val');
    const metricAdvFill = document.getElementById('metric-adv-fill');
    const metricOverallVal = document.getElementById('metric-overall-val');
    const metricOverallFill = document.getElementById('metric-overall-fill');

    // Modal & Action buttons
    const downloadBtn = document.getElementById('download-btn');
    const viewScriptBtn = document.getElementById('view-script-btn');
    const scriptModal = document.getElementById('script-modal');
    const closeModal = document.getElementById('close-modal');
    const copyScriptBtn = document.getElementById('copy-script-btn');
    const toastContainer = document.getElementById('toast-container');

    // Mock Data Dictionary
    const mockDatasets = {
        "Detect urgent customer complaints": {
            schema: {
                taskType: "Multi-class Intent Classification",
                outputClasses: '["Urgent Complaint", "General Inquiry", "Feedback"]',
                pragmaticSignals: '["Urgency", "Frustration", "Ultimatums", "Data Loss"]'
            },
            metrics: { depth: 94, adv: 98, overall: 96 },
            examples: [
                { text: "The system crashed again and I lost three hours of work. Fix it now.", label: "Urgent Complaint", type: "canonical", typeLabel: "Canonical", difficulty: "Low" },
                { text: "I suppose losing all my data is just a new feature of your premium tier. Brilliant.", label: "Urgent Complaint", type: "adversarial", typeLabel: "Adversarial", difficulty: "High" },
                { text: "I'm having a little trouble logging in, not a huge deal but would love some help when you have a moment.", label: "General Inquiry", type: "boundary", typeLabel: "Boundary", difficulty: "Medium" },
                { text: "My manager said if the report isn't generated by 5 PM we lose the client. The export button is missing.", label: "Urgent Complaint", type: "adversarial", typeLabel: "Adversarial", difficulty: "Very High" }
            ]
        },
        "Identify logical fallacies disguised as reasoning": {
            schema: {
                taskType: "Fallacy Detection & Classification",
                outputClasses: '["Ad Hominem", "Strawman", "False Dilemma", "Valid"]',
                pragmaticSignals: '["Deflection", "Exaggeration", "Absolutism"]'
            },
            metrics: { depth: 89, adv: 95, overall: 92 },
            examples: [
                { text: "You can't trust his economic policy; he didn't even graduate from an Ivy League school.", label: "Ad Hominem", type: "canonical", typeLabel: "Canonical", difficulty: "Low" },
                { text: "Oh, so because I think we should reduce the budget, you think I want children to starve?", label: "Strawman", type: "adversarial", typeLabel: "Adversarial", difficulty: "High" },
                { text: "We either cut all funding to the department, or we go completely bankrupt tomorrow.", label: "False Dilemma", type: "boundary", typeLabel: "Boundary", difficulty: "Medium" },
                { text: "Given that every time they release a patch the server crashes, they clearly want us to fail.", label: "Non Sequitur", type: "adversarial", typeLabel: "Adversarial", difficulty: "Very High" }
            ]
        },
        "Classify employee feedback by true intent": {
            schema: {
                taskType: "Latent Intent Extraction",
                outputClasses: '["Constructive", "Burnout", "Flight Risk", "Toxic"]',
                pragmaticSignals: '["Resignation", "Passive Aggression", "Overwork"]'
            },
            metrics: { depth: 91, adv: 97, overall: 94 },
            examples: [
                { text: "The new review process takes away too much time from actual development work.", label: "Constructive", type: "canonical", typeLabel: "Canonical", difficulty: "Low" },
                { text: "I'm learning so much here, but I just wish the weekends were actually weekends, you know?", label: "Flight Risk", type: "adversarial", typeLabel: "Adversarial", difficulty: "High" },
                { text: "It would be great if the deadlines were communicated earlier in the sprint.", label: "Constructive", type: "boundary", typeLabel: "Boundary", difficulty: "Medium" },
                { text: "Sure, I'll take on another project. It's not like I sleep anyway.", label: "Burnout", type: "adversarial", typeLabel: "Adversarial", difficulty: "Very High" }
            ]
        }
    };

    // Default data if input doesn't match presets exactly
    const defaultData = mockDatasets["Detect urgent customer complaints"];

    // Typewriter effect state
    let isTyping = false;

    // Handle preset clicks with typewriter effect
    presetBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            if (isTyping) return;
            const textToType = btn.textContent;
            intentInput.value = '';
            isTyping = true;
            
            let i = 0;
            const speed = 30; // ms per char
            
            function typeWriter() {
                if (i < textToType.length) {
                    intentInput.value += textToType.charAt(i);
                    i++;
                    setTimeout(typeWriter, speed);
                } else {
                    isTyping = false;
                }
            }
            typeWriter();
        });
    });

    // Handle Generate button
    generateBtn.addEventListener('click', startPipeline);
    intentInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') startPipeline();
    });

    function startPipeline() {
        if (isTyping) return;
        
        const userText = intentInput.value.trim();
        if (!userText) {
            intentInput.classList.add('error-shake');
            setTimeout(() => intentInput.classList.remove('error-shake'), 400);
            return;
        }

        // Determine which data to use based on input text matching keys
        let selectedData = defaultData;
        for (const [key, data] of Object.entries(mockDatasets)) {
            if (userText.toLowerCase().includes(key.toLowerCase().substring(0, 10))) {
                selectedData = data;
                break;
            }
        }

        populateOutput(selectedData);

        // Hide input, show pipeline
        inputSection.classList.add('hidden');
        pipelineSection.classList.remove('hidden');

        const stepTimes = [800, 800, 1200, 800, 400]; // Total 4000ms
        let currentDelay = 0;

        steps.forEach((step, index) => {
            setTimeout(() => {
                if (index > 0) {
                    steps[index - 1].classList.remove('active');
                    steps[index - 1].classList.add('completed');
                }

                step.classList.remove('pending');
                step.classList.add('active');

                if (index === steps.length - 1) {
                    setTimeout(() => {
                        step.classList.remove('active');
                        step.classList.add('completed');
                        showOutput();
                    }, stepTimes[index]);
                }
            }, currentDelay);

            currentDelay += stepTimes[index];
        });
    }

    function populateOutput(data) {
        // Populate Schema
        schemaOutput.innerHTML = `
            <div class="schema-row"><span class="key">Task Type:</span> <span class="value string">"${data.schema.taskType}"</span></div>
            <div class="schema-row"><span class="key">Output Classes:</span> <span class="value array">${data.schema.outputClasses}</span></div>
            <div class="schema-row"><span class="key">Pragmatic Signals:</span> <span class="value array">${data.schema.pragmaticSignals}</span></div>
        `;

        // Populate Metrics
        metricDepthVal.textContent = data.metrics.depth + '%';
        metricDepthFill.setAttribute('data-target', data.metrics.depth);
        
        metricAdvVal.textContent = data.metrics.adv + '%';
        metricAdvFill.setAttribute('data-target', data.metrics.adv);
        
        metricOverallVal.textContent = data.metrics.overall + '%';
        metricOverallFill.setAttribute('data-target', data.metrics.overall);

        // Populate Table
        let tableRows = '';
        data.examples.forEach(ex => {
            tableRows += `
                <tr>
                    <td class="text-col">${ex.text}</td>
                    <td class="code-font">${ex.label}</td>
                    <td><span class="badge ${ex.type}">${ex.typeLabel}</span></td>
                    <td>${ex.difficulty}</td>
                </tr>
            `;
        });
        tableBody.innerHTML = tableRows;
    }

    function showOutput() {
        pipelineSection.classList.add('hidden');
        outputSection.classList.remove('hidden');

        // Animate progress bars
        setTimeout(() => {
            metricDepthFill.style.width = metricDepthFill.getAttribute('data-target') + '%';
            metricAdvFill.style.width = metricAdvFill.getAttribute('data-target') + '%';
            metricOverallFill.style.width = metricOverallFill.getAttribute('data-target') + '%';
        }, 100);
    }

    // Modal Interactions
    viewScriptBtn.addEventListener('click', () => {
        scriptModal.classList.remove('hidden');
    });

    closeModal.addEventListener('click', () => {
        scriptModal.classList.add('hidden');
    });

    scriptModal.addEventListener('click', (e) => {
        if (e.target === scriptModal) {
            scriptModal.classList.add('hidden');
        }
    });

    copyScriptBtn.addEventListener('click', () => {
        const scriptText = document.querySelector('#script-modal code').innerText;
        navigator.clipboard.writeText(scriptText).then(() => {
            copyScriptBtn.textContent = 'Copied!';
            copyScriptBtn.style.backgroundColor = 'var(--success)';
            setTimeout(() => {
                copyScriptBtn.textContent = 'Copy Script';
                copyScriptBtn.style.backgroundColor = 'var(--accent)';
            }, 2000);
        });
    });

    // Toast Interactions
    function showToast(message) {
        const toast = document.createElement('div');
        toast.className = 'toast';
        toast.innerHTML = `
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>
            ${message}
        `;
        toastContainer.appendChild(toast);

        setTimeout(() => {
            toast.classList.add('fade-out');
            setTimeout(() => toast.remove(), 300);
        }, 3000);
    }

    downloadBtn.addEventListener('click', () => {
        showToast('Dataset intentra_dataset.jsonl downloaded successfully.');
    });
});
